version: '3'

services:

  track:
    build:
      context: .
      dockerfile: ./track-library-service/Dockerfile
    ports:
      - "80:80"

  rec:
    build:
      context: .
      dockerfile: ./recommendation-service/Dockerfile
    ports:
      - "81:81"

volumes:
  postgres_data:
