version: '3'

services:

  track:
    build:
      context: .
      dockerfile: ./track-library-service/Dockerfile
    ports:
      - "80:80"

  rec:
    build:
      context: .
      dockerfile: ./recommendation-service/Dockerfile
    ports:
      - "81:81"

#  keycloak:
#    image: quay.io/keycloak/keycloak:23.0.1
#    ports:
#      - "8080:8080"
#    environment:
#      - KEYCLOAK_ADMIN=admin
#      - KEYCLOAK_ADMIN_PASSWORD=admin
#    command: "start-dev"



volumes:
  postgres_data:
