version: '3'

services:


  #  rabbitmq:
  #    image: "rabbitmq:management"
  #    environment:
  #      RABBITMQ_DEFAULT_USER: guest
  #      RABBITMQ_DEFAULT_PASS: guest
  #    ports:
  #      - "5672:5672"
  #      - "15672:15672"

  track:
    build:

      context: .
      dockerfile: ./track-library-service/Dockerfile
    ports:
      - "80:80"


  rec:
    build:
      context: .
      dockerfile: ./recommendation-service/Dockerfile
    ports:
      - "81:81"




volumes:
  postgres_data:
